---
- name: Allow DNS (TCP) through UFW
  community.general.ufw:
    rule: allow
    port: "53"
    proto: tcp
    comment: AdGuard DNS

- name: Allow DNS (UDP) through UFW
  community.general.ufw:
    rule: allow
    port: "53"
    proto: udp
    comment: AdGuard DNS

- name: Allow AdGuard web UI through UFW
  community.general.ufw:
    rule: allow
    port: "3000"
    proto: tcp
    comment: AdGuard setup UI

- name: Allow AdGuard dashboard through UFW
  community.general.ufw:
    rule: allow
    port: "8080"
    proto: tcp
    comment: AdGuard dashboard
