---
galaxy_info:
  author: emre
  description: Maintainerr - auto-delete watched media
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm

dependencies:
  - docker
